SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
WHERE EXTRACT(YEAR FROM BS.SALES_DATE) = 2022
  AND EXTRACT(MONTH FROM BS.SALES_DATE) = 1
GROUP BY
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY
ORDER BY
    B.AUTHOR_ID ASC,
    B.CATEGORY DESC;