WITH RECURSIVE Generation_CTE AS (
    -- 1. 1세대 (부모가 없는 대장균)
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 2. 자식 대장균 (부모의 세대 + 1)
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN Generation_CTE G ON E.PARENT_ID = G.ID
)
SELECT ID
FROM Generation_CTE
WHERE GENERATION = 3
ORDER BY ID ASC;
