SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
JOIN (
    -- 음식 종류별 최대 즐겨찾기 수 계산
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) MAX_RI
ON RI.FOOD_TYPE = MAX_RI.FOOD_TYPE AND RI.FAVORITES = MAX_RI.MAX_FAV
ORDER BY RI.FOOD_TYPE DESC;
