SELECT   A.REST_ID,
         B.REST_NAME,
         B.FOOD_TYPE,
         B.FAVORITES,
         B.ADDRESS,
         ROUND(AVG(A.REVIEW_SCORE), 2) AS SCORE
FROM     REST_REVIEW A
JOIN     REST_INFO B ON A.REST_ID = B.REST_ID
WHERE    B.ADDRESS LIKE '서울%'     -- WHERE로 옮기는 것이 자연스럽습니다
GROUP BY A.REST_ID,
         B.REST_NAME,
         B.FOOD_TYPE,
         B.FAVORITES,
         B.ADDRESS
ORDER BY SCORE DESC, B.FAVORITES DESC;