SELECT
    H.HISTORY_ID,
    FLOOR(
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN
                C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
                * (100 - P90.DISCOUNT_RATE) / 100
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN
                C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
                * (100 - P30.DISCOUNT_RATE) / 100
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN
                C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
                * (100 - P7.DISCOUNT_RATE) / 100
            ELSE
                C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
        END
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P7
    ON C.CAR_TYPE = P7.CAR_TYPE
   AND P7.DURATION_TYPE = '7일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P30
    ON C.CAR_TYPE = P30.CAR_TYPE
   AND P30.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P90
    ON C.CAR_TYPE = P90.CAR_TYPE
   AND P90.DURATION_TYPE = '90일 이상'
WHERE C.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC,
    H.HISTORY_ID DESC;