SELECT FLAVOR
   FROM (
        SELECT FLAVOR, SUM(TOT_PRICE)
        , RANK() OVER (ORDER BY SUM(TOT_PRICE) DESC) AS RESULT
          FROM (
              SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT_PRICE
                FROM JULY
             GROUP BY FLAVOR
             UNION ALL
              SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT_PRICE
                FROM FIRST_HALF
              GROUP BY FLAVOR
          )
         GROUP BY FLAVOR
)
WHERE RESULT <= 3;