SELECT H.HOUR,
       NVL(C.CNT, 0) AS COUNT
FROM (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) H
LEFT JOIN (
    SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
           COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
) C
ON H.HOUR = C.HOUR
ORDER BY H.HOUR;