SELECT
    EXTRACT(MONTH FROM H.START_DATE) AS MONTH,
    H.CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE H.START_DATE >= DATE '2022-08-01'
  AND H.START_DATE < DATE '2022-11-01'
  AND H.CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE >= DATE '2022-08-01'
          AND START_DATE < DATE '2022-11-01'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY
    EXTRACT(MONTH FROM H.START_DATE),
    H.CAR_ID
HAVING COUNT(*) > 0
ORDER BY
    MONTH ASC,
    CAR_ID DESC;